### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by nicolasgome** [colegio-seminario-diocesano-de-duitama/Chivas-Team-1101-#1]

**Comment by MarcyMateus** [comment]
![PictóricoChivas](https://user-images.githubusercontent.com/47117506/57187772-b0756700-6eb9-11e9-99ee-4ca68db034cf.png)
![EsquemáticoChivas](https://user-images.githubusercontent.com/47117506/57187774-b53a1b00-6eb9-11e9-8588-85e80ee32798.png)
[PlanoCarroBluetooth.pdf](https://github.com/colegio-seminario-diocesano-de-duitama/Chivas-Team-1101-/files/3145086/PlanoCarroBluetooth.pdf)
